---
title: "cram-comments"
author: "Charlie Beirnaert"
date: "`r Sys.Date()`"
output: md_document
---
## speaq2 vs speaq:
Both speaq and speaq2 was developed in our research group but speaq2 is so fundamentally different than speaq that we deemed it belonged in a different package. Speaq however will not be discontinued and is still in an active state (both on the user as the developper end).

## Bioconductor 
MassSpecWavelet is a Bioconductor package.

## Test environments
* local OS X install, R 3.3.2
* devtools win-builder, R-oldrelease 
* devtools win-builder, R-release (3.4.0)
* devtools win-builder, R devel (unstable) (2017-05-11 r72669)
* travis.ci Linux, x64, R oldrel (3.3.3)
* travis.ci Linux, x64, R release (3.4.0)
* travis.ci Linux, x64, R devel (unstable) (2017-05-12 r72670)


## R CMD check results
There were no ERRORs or WARNINGs.

Local OS X build generated no NOTEs

Travis.ci generated 1 NOTE

Win-builder generated NOTEs

* new package maintainer: Under mutual agreement with Trung Nghia Vu (nghiavtr@gmail.com) I will take over the package maintenance.

* Uses the superseded package: 'doSNOW': this is to provide progress bars when performing parallel computations (not available in doParallel so far). When this option is avalaible in doParallel the switch to this package will be made.

* possibly mis-spelled words in DESCRIPTION: These words are not mis-spelled.

* package size is 5.4 Mb. This is because it includes 2 vignettes, for the 2 main methods in the package and also because a dataset is included.


## Downstream dependencies
I have also run R CMD check on downstream dependencies of speaq. 
All packages passed.